
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - APP_ENV=dev
      - APP_SECRET=bba3e9d2347f83df4f2104d76898205c
    volumes:
      - ./var:/var/www/html/var
    depends_on:
      - mailer

volumes:
